USE Teste_BDII;
GO

-- Criação das Tabelas
CREATE TABLE NOTA_FISCAL (
    NRO_NOTA INT IDENTITY(1,1) PRIMARY KEY,
    NM_CLIENTE VARCHAR(256) NOT NULL,
    END_CLIENTE VARCHAR(256) NOT NULL,
    NM_VENDEDOR VARCHAR(256) NOT NULL,
    DT_EMISSAO DATETIME DEFAULT GETDATE(),
    VL_TOTAL DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE PRODUTO (
    COD_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    DESC_PRODUTO VARCHAR(256) NOT NULL,
    UN_MED CHAR(2) NOT NULL,
    VL_PRODUTO DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE ITEM_NOTA_FISCAL (
    NRO_NOTA INT NOT NULL,
    COD_PRODUTO INT NOT NULL,
    QTD_PRODUTO INT NOT NULL,
    VL_PRECO DECIMAL(10,2) NOT NULL,
    VL_TOTAL DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (NRO_NOTA, COD_PRODUTO),
    CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL(NRO_NOTA),
    CONSTRAINT FK_COD_PRODUTO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);
GO

-- Inserção de Produtos
INSERT INTO PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES 
('Leite', 'LT', 4.50),
('Desodorante', 'UN', 8.00),
('Refrigerante', 'UN', 10.00);
GO

-- Inserção de Notas Fiscais
INSERT INTO NOTA_FISCAL (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES 
('Aragorn', 'Terra Média', 'Bilbo', 100.00),
('Gandalf', 'Terra Média', 'Frodo', 100.00),
('Gandalf', 'Terra Média', 'Frodo', 100.00),
('Boromir', 'Mordor', 'Sam', 100.00),
('Galadriel', 'Valinor', 'Saruman', 100.00);
GO

-- Inserção de Itens da Nota Fiscal
-- Obs: COD_PRODUTO vai de 1 a 3, conforme os inseridos
INSERT INTO ITEM_NOTA_FISCAL (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES 
(1, 1, 1, 4.50, 4.50),
(1, 2, 2, 8.00, 16.00),
(2, 2, 1, 8.00, 8.00),
(4, 3, 10, 10.00, 100.00),
(5, 1, 2, 4.50, 9.00);
GO
